// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer → Kolom 1*
 */
export interface FooterDocumentDataColumn1Item {
  /**
   * Item field in *Footer → Kolom 1*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.column_1[].item
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  item: prismic.RichTextField;
}

/**
 * Item in *Footer → Kolom 2*
 */
export interface FooterDocumentDataColumn2Item {
  /**
   * Item field in *Footer → Kolom 2*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.column_2[].item
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  item: prismic.RichTextField;
}

/**
 * Item in *Footer → Kolom 3*
 */
export interface FooterDocumentDataColumn3Item {
  /**
   * Item field in *Footer → Kolom 3*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.column_3[].item
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  item: prismic.RichTextField;
}

/**
 * Item in *Footer → Kolom 4*
 */
export interface FooterDocumentDataColumn4Item {
  /**
   * Item field in *Footer → Kolom 4*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.column_4[].item
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  item: prismic.RichTextField;
}

/**
 * Item in *Footer → Beleid links*
 */
export interface FooterDocumentDataLinksGroupItem {
  /**
   * Link field in *Footer → Beleid links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_group[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link label field in *Footer → Beleid links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_group[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Titel kolom 1 field in *Footer*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title_column_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_column_1: prismic.TitleField;

  /**
   * Kolom 1 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.column_1[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  column_1: prismic.GroupField<Simplify<FooterDocumentDataColumn1Item>>;

  /**
   * Titel kolom 2 field in *Footer*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title_column_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_column_2: prismic.TitleField;

  /**
   * Kolom 2 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.column_2[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  column_2: prismic.GroupField<Simplify<FooterDocumentDataColumn2Item>>;

  /**
   * Titel kolom 3 field in *Footer*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title_column_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_column_3: prismic.TitleField;

  /**
   * Kolom 3 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.column_3[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  column_3: prismic.GroupField<Simplify<FooterDocumentDataColumn3Item>>;

  /**
   * Titel kolom 4 field in *Footer*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title_column_4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_column_4: prismic.TitleField;

  /**
   * Kolom 4 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.column_4[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  column_4: prismic.GroupField<Simplify<FooterDocumentDataColumn4Item>>;

  /**
   * Beleid links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_group[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_group: prismic.GroupField<Simplify<FooterDocumentDataLinksGroupItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type NavigatieDocumentDataSlicesSlice = NavigatieItemSlice;

/**
 * Content for Navigatie documents
 */
interface NavigatieDocumentData {
  /**
   * Slice Zone field in *Navigatie*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigatie.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigatieDocumentDataSlicesSlice>;
}

/**
 * Navigatie document from Prismic
 *
 * - **API ID**: `navigatie`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigatieDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigatieDocumentData>,
    "navigatie",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ContactSlice
  | CollageSlice
  | ParagraafSlice
  | CollectiesSlice
  | AfbeeldingMetTekstSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Parent page field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | NavigatieDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *AfbeeldingMetTekst → Primary*
 */
export interface AfbeeldingMetTekstSliceDefaultPrimary {
  /**
   * Achtergrond kleur field in *AfbeeldingMetTekst → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Kleur 1
   * - **API ID Path**: afbeelding_met_tekst.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<"Kleur 1" | "Kleur 2", "filled">;

  /**
   * Positie afbeelding field in *AfbeeldingMetTekst → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Links
   * - **API ID Path**: afbeelding_met_tekst.primary.image_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_position: prismic.SelectField<"Links" | "Rechts", "filled">;

  /**
   * Tekst uitlijning field in *AfbeeldingMetTekst → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Links
   * - **API ID Path**: afbeelding_met_tekst.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_alignment: prismic.SelectField<"Links" | "Midden", "filled">;

  /**
   * Titel field in *AfbeeldingMetTekst → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: afbeelding_met_tekst.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Paragraaf field in *AfbeeldingMetTekst → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: afbeelding_met_tekst.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Button Label field in *AfbeeldingMetTekst → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: afbeelding_met_tekst.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button link field in *AfbeeldingMetTekst → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: afbeelding_met_tekst.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Image field in *AfbeeldingMetTekst → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: afbeelding_met_tekst.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AfbeeldingMetTekst Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AfbeeldingMetTekstSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AfbeeldingMetTekstSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AfbeeldingMetTekst*
 */
type AfbeeldingMetTekstSliceVariation = AfbeeldingMetTekstSliceDefault;

/**
 * AfbeeldingMetTekst Shared Slice
 *
 * - **API ID**: `afbeelding_met_tekst`
 * - **Description**: AfbeeldingMetTekst
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AfbeeldingMetTekstSlice = prismic.SharedSlice<
  "afbeelding_met_tekst",
  AfbeeldingMetTekstSliceVariation
>;

/**
 * Primary content in *Collage → Items*
 */
export interface CollageSliceDefaultItem {
  /**
   * Afbeelding field in *Collage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collage.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Collage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CollageSliceDefaultItem>
>;

/**
 * Slice variation for *Collage*
 */
type CollageSliceVariation = CollageSliceDefault;

/**
 * Collage Shared Slice
 *
 * - **API ID**: `collage`
 * - **Description**: Collage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollageSlice = prismic.SharedSlice<
  "collage",
  CollageSliceVariation
>;

/**
 * Primary content in *Collecties → Primary*
 */
export interface CollectiesSliceDefaultPrimary {
  /**
   * Titel field in *Collecties → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: collecties.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Paragraaf field in *Collecties → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collecties.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Tekst uitlijning field in *Collecties → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Links
   * - **API ID Path**: collecties.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_alignment: prismic.SelectField<"Links" | "Midden", "filled">;
}

/**
 * Primary content in *Collecties → Items*
 */
export interface CollectiesSliceDefaultItem {
  /**
   * Categorie Link field in *Collecties → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: collecties.items[].category_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category_link: prismic.LinkField;

  /**
   * Categorie Naam field in *Collecties → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: collecties.items[].category_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  category_name: prismic.TitleField;

  /**
   * Categorie Afbeeldign field in *Collecties → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collecties.items[].category_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  category_image: prismic.ImageField<never>;
}

/**
 * Default variation for Collecties Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollectiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CollectiesSliceDefaultPrimary>,
  Simplify<CollectiesSliceDefaultItem>
>;

/**
 * Slice variation for *Collecties*
 */
type CollectiesSliceVariation = CollectiesSliceDefault;

/**
 * Collecties Shared Slice
 *
 * - **API ID**: `collecties`
 * - **Description**: Collecties
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollectiesSlice = prismic.SharedSlice<
  "collecties",
  CollectiesSliceVariation
>;

/**
 * Primary content in *Contact → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Naam veld field in *Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Telefoonnummer veld field in *Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Email veld field in *Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Bericht veld field in *Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primary.message
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message: prismic.KeyTextField;

  /**
   * Button field in *Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primary.button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Titel field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Paragraaf field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Button label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Afbeelding field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *NavigatieItem → Primary*
 */
export interface NavigatieItemSliceDefaultPrimary {
  /**
   * Label field in *NavigatieItem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigatie_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Link field in *NavigatieItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigatie_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Navigatie Item variation for NavigatieItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigatieItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigatieItemSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *NavigatieItem → Primary*
 */
export interface NavigatieItemSliceNavigatieItemMetDropdownPrimary {
  /**
   * Label field in *NavigatieItem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigatie_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Link field in *NavigatieItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigatie_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *NavigatieItem → Items*
 */
export interface NavigatieItemSliceNavigatieItemMetDropdownItem {
  /**
   * Label field in *NavigatieItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigatie_item.items[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Link field in *NavigatieItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigatie_item.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Navigatie Item met Dropdown variation for NavigatieItem Slice
 *
 * - **API ID**: `navigatieItemMetDropdown`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigatieItemSliceNavigatieItemMetDropdown =
  prismic.SharedSliceVariation<
    "navigatieItemMetDropdown",
    Simplify<NavigatieItemSliceNavigatieItemMetDropdownPrimary>,
    Simplify<NavigatieItemSliceNavigatieItemMetDropdownItem>
  >;

/**
 * Slice variation for *NavigatieItem*
 */
type NavigatieItemSliceVariation =
  | NavigatieItemSliceDefault
  | NavigatieItemSliceNavigatieItemMetDropdown;

/**
 * NavigatieItem Shared Slice
 *
 * - **API ID**: `navigatie_item`
 * - **Description**: NavigatieItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigatieItemSlice = prismic.SharedSlice<
  "navigatie_item",
  NavigatieItemSliceVariation
>;

/**
 * Primary content in *Paragraaf → Primary*
 */
export interface ParagraafSliceDefaultPrimary {
  /**
   * Titel field in *Paragraaf → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: paragraaf.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Paragraaf field in *Paragraaf → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: paragraaf.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Default variation for Paragraaf Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagraafSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ParagraafSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Paragraaf*
 */
type ParagraafSliceVariation = ParagraafSliceDefault;

/**
 * Paragraaf Shared Slice
 *
 * - **API ID**: `paragraaf`
 * - **Description**: Paragraaf
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagraafSlice = prismic.SharedSlice<
  "paragraaf",
  ParagraafSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataColumn1Item,
      FooterDocumentDataColumn2Item,
      FooterDocumentDataColumn3Item,
      FooterDocumentDataColumn4Item,
      FooterDocumentDataLinksGroupItem,
      NavigatieDocument,
      NavigatieDocumentData,
      NavigatieDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      AfbeeldingMetTekstSlice,
      AfbeeldingMetTekstSliceDefaultPrimary,
      AfbeeldingMetTekstSliceVariation,
      AfbeeldingMetTekstSliceDefault,
      CollageSlice,
      CollageSliceDefaultItem,
      CollageSliceVariation,
      CollageSliceDefault,
      CollectiesSlice,
      CollectiesSliceDefaultPrimary,
      CollectiesSliceDefaultItem,
      CollectiesSliceVariation,
      CollectiesSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      NavigatieItemSlice,
      NavigatieItemSliceDefaultPrimary,
      NavigatieItemSliceNavigatieItemMetDropdownPrimary,
      NavigatieItemSliceNavigatieItemMetDropdownItem,
      NavigatieItemSliceVariation,
      NavigatieItemSliceDefault,
      NavigatieItemSliceNavigatieItemMetDropdown,
      ParagraafSlice,
      ParagraafSliceDefaultPrimary,
      ParagraafSliceVariation,
      ParagraafSliceDefault,
    };
  }
}
