// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  afbeelding_met_tekst: dynamic(() => import("./AfbeeldingMetTekst")),
  collage: dynamic(() => import("./Collage")),
  collecties: dynamic(() => import("./Collecties")),
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  navigatie_item: dynamic(() => import("./NavigatieItem")),
  paragraaf: dynamic(() => import("./Paragraaf")),
};
