// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  afbeelding_met_tekst: dynamic(() => import("./AfbeeldingMetTekst")),
  collecties: dynamic(() => import("./Collecties")),
  hero: dynamic(() => import("./Hero")),
  navigatie_item: dynamic(() => import("./NavigatieItem")),
};
